@host = localhost:4004

####################################
# READING
####################################

# @name foundBooks
GET /odata/v4/catalog/Books
    # ?$filter=(IsActiveEntity eq false or SiblingEntity/IsActiveEntity eq null)
    ?$filter=(IsActiveEntity eq false)
    &$count=true
Host: {{host}}

###

####################################
# EDITING
####################################

# Create first book
# @name createdBook
POST /odata/v4/catalog/Books
Host: {{host}}
Content-Type: application/json

{
    "title": "Harry Potter and the Half-Blood Prince",
    "publishedOn": "2005-07-16"
}

###

# Set stock to invalid value
PATCH /odata/v4/catalog/Books(ID={{createdBook.response.body.ID}},IsActiveEntity=false)
Host: {{host}}
Content-Type: application/json

{
    "stock": 2000
}

###

# Create second book
# @name createdBook
POST /odata/v4/catalog/Books
Host: {{host}}
Content-Type: application/json

{
    "title": "Witcher 3",
    "publishedOn": "2015-07-16"
}

###

# Delete a book
DELETE /odata/v4/catalog/Books(ID={{foundBooks.response.body.value[0].ID}},IsActiveEntity=true)
Host: {{host}}

###

############################################
# ACTIVATION
############################################

# Draft prepare
POST /odata/v4/catalog/Books(ID={{createdBook.response.body.ID}},IsActiveEntity=false)/CatalogService.draftPrepare 
Host: {{host}}
Content-Type: application/json

{}

###

# Draft activate
POST /odata/v4/catalog/Books(ID={{createdBook.response.body.ID}},IsActiveEntity=false)/CatalogService.draftActivate 
Host: {{host}}
Content-Type: application/json

{}

### sum 2 numbers
POST /odata/v4/catalog/sum
Host: {{host}}
Content-Type: application/json

{"x": 4, "y": 5}


### lock employee
POST /odata/v4/catalog/Employees(id=1149184,employeeId=1149184)/lock
Host: {{host}}
Content-Type: application/json

{ "endDate": "9999-12-31" }

### Buy Book
POST /odata/v4/catalog/Books(ID=cdb33d05-bd0e-4c47-97b6-aa5df2f2c717,IsActiveEntity=true)/buy
Host: {{host}}
Content-Type: application/json

{ "amount": 4 }

### change leader of company
POST /odata/v4/catalog/Companies(ID='google')/changeLeader
Host: {{host}}
Content-Type: application/json

{ "leaderName": "John Doe"}