# @name token
POST {{$dotenv uaaUrl}}/oauth/token
Authorization: Basic {{$dotenv clientId}}:{{$dotenv clientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{$dotenv user}}
&password={{$dotenv pw}}

###

@server = {{$dotenv appUrl}}
@auth = Authorization: Bearer {{token.response.body.access_token}}
# @server = http://localhost:4004
# @auth = Authorization: Basic Alice:

###
GET {{server}}/odata/v4/my/Books
{{auth}}
Content-Type: application/json

###
POST {{server}}/odata/v4/my/Books
Content-Type: application/json
{{auth}}

{
    "title": "Harry Potter and the Half-Blood Prince"
}

###
PATCH {{server}}/odata/v4/my/Books
Content-Type: application/json
{{auth}}

{}

###
DELETE {{server}}/odata/v4/my/Books
{{auth}}

###
GET {{server}}/odata/v4/my/Regions
{{auth}}
Content-Type: application/json

###
POST {{server}}/odata/v4/my/Regions
Content-Type: application/json
{{auth}}

{}

###
PATCH {{server}}/odata/v4/my/Regions
Content-Type: application/json
{{auth}}

{}

###
DELETE {{server}}/odata/v4/my/Regions
{{auth}}
