// This is an automatically generated file. Please do not change its contents manually!
const cds = require('@sap/cds')
const csn = cds.entities('API_PRODUCT')
module.exports = { name: 'API_PRODUCT' }
module.exports.A_Product = csn.A_Product
module.exports.A_Product_ = csn.A_Product
module.exports.A_ProductBasicText = csn.A_ProductBasicText
module.exports.A_ProductBasicText_ = csn.A_ProductBasicText
module.exports.A_ProductDescription = csn.A_ProductDescription
module.exports.A_ProductDescription_ = csn.A_ProductDescription
module.exports.A_ProductInspectionText = csn.A_ProductInspectionText
module.exports.A_ProductInspectionText_ = csn.A_ProductInspectionText
module.exports.A_ProductMLAccount = csn.A_ProductMLAccount
module.exports.A_ProductMLAccount_ = csn.A_ProductMLAccount
module.exports.A_ProductMLPrice = csn.A_ProductMLPrices
module.exports.A_ProductMLPrices = csn.A_ProductMLPrices
module.exports.A_ProductPlant = csn.A_ProductPlant
module.exports.A_ProductPlant_ = csn.A_ProductPlant
module.exports.A_ProductPlantCosting = csn.A_ProductPlantCosting
module.exports.A_ProductPlantCosting_ = csn.A_ProductPlantCosting
module.exports.A_ProductPlantForecasting = csn.A_ProductPlantForecasting
module.exports.A_ProductPlantForecasting_ = csn.A_ProductPlantForecasting
module.exports.A_ProductPlantIntlTrd = csn.A_ProductPlantIntlTrd
module.exports.A_ProductPlantIntlTrd_ = csn.A_ProductPlantIntlTrd
module.exports.A_ProductPlantMRPArea = csn.A_ProductPlantMRPArea
module.exports.A_ProductPlantMRPArea_ = csn.A_ProductPlantMRPArea
module.exports.A_ProductPlantProcurement = csn.A_ProductPlantProcurement
module.exports.A_ProductPlantProcurement_ = csn.A_ProductPlantProcurement
module.exports.A_ProductPlantQualityMgmt = csn.A_ProductPlantQualityMgmt
module.exports.A_ProductPlantQualityMgmt_ = csn.A_ProductPlantQualityMgmt
module.exports.A_ProductPlantSale = csn.A_ProductPlantSales
module.exports.A_ProductPlantSales = csn.A_ProductPlantSales
module.exports.A_ProductPlantStorage = csn.A_ProductPlantStorage
module.exports.A_ProductPlantStorage_ = csn.A_ProductPlantStorage
module.exports.A_ProductPlantText = csn.A_ProductPlantText
module.exports.A_ProductPlantText_ = csn.A_ProductPlantText
module.exports.A_ProductProcurement = csn.A_ProductProcurement
module.exports.A_ProductProcurement_ = csn.A_ProductProcurement
module.exports.A_ProductPurchaseText = csn.A_ProductPurchaseText
module.exports.A_ProductPurchaseText_ = csn.A_ProductPurchaseText
module.exports.A_ProductQualityMgmt = csn.A_ProductQualityMgmt
module.exports.A_ProductQualityMgmt_ = csn.A_ProductQualityMgmt
module.exports.A_ProductSale = csn.A_ProductSales
module.exports.A_ProductSales = csn.A_ProductSales
module.exports.A_ProductSalesDelivery = csn.A_ProductSalesDelivery
module.exports.A_ProductSalesDelivery_ = csn.A_ProductSalesDelivery
module.exports.A_ProductSalesTax = csn.A_ProductSalesTax
module.exports.A_ProductSalesTax_ = csn.A_ProductSalesTax
module.exports.A_ProductSalesText = csn.A_ProductSalesText
module.exports.A_ProductSalesText_ = csn.A_ProductSalesText
module.exports.A_ProductStorage = csn.A_ProductStorage
module.exports.A_ProductStorage_ = csn.A_ProductStorage
module.exports.A_ProductStorageLocation = csn.A_ProductStorageLocation
module.exports.A_ProductStorageLocation_ = csn.A_ProductStorageLocation
module.exports.A_ProductSupplyPlanning = csn.A_ProductSupplyPlanning
module.exports.A_ProductSupplyPlanning_ = csn.A_ProductSupplyPlanning
module.exports.A_ProductUnitsOfMeasure = csn.A_ProductUnitsOfMeasure
module.exports.A_ProductUnitsOfMeasure_ = csn.A_ProductUnitsOfMeasure
module.exports.A_ProductUnitsOfMeasureEAN = csn.A_ProductUnitsOfMeasureEAN
module.exports.A_ProductUnitsOfMeasureEAN_ = csn.A_ProductUnitsOfMeasureEAN
module.exports.A_ProductValuation = csn.A_ProductValuation
module.exports.A_ProductValuation_ = csn.A_ProductValuation
module.exports.A_ProductValuationAccount = csn.A_ProductValuationAccount
module.exports.A_ProductValuationAccount_ = csn.A_ProductValuationAccount
module.exports.A_ProductValuationCosting = csn.A_ProductValuationCosting
module.exports.A_ProductValuationCosting_ = csn.A_ProductValuationCosting
module.exports.A_ProductWorkScheduling = csn.A_ProductWorkScheduling
module.exports.A_ProductWorkScheduling_ = csn.A_ProductWorkScheduling
// events
// actions
// enums
